### ISSUE TITLE
in portfolio add non wanted coin

### ISSUE THREAD

**Issue by ronki2304** [miguelmota/cointop#136] opened 2021-08-17 13:15 UTC
Hello team,

if you add auto token (from autofarm) in your portfolio, other token with i suppose the same coin identifier are added :
![image](https://user-images.githubusercontent.com/25466164/129732236-50aacb96-34cb-48eb-ac58-dedf78a38884.png)

is it possible to remove them

thank you in advance

**Comment by simon-anz** [comment] 2021-08-18 02:46
Duplicate of #130

**Comment by miguelmota** [comment] 2021-08-22 11:13
Closed by https://github.com/miguelmota/cointop/pull/138

**Closed by miguelmota** 2021-08-22 11:13 UTC
