### ISSUE TITLE
brew install cointop && cointop - current map writes

### ISSUE THREAD

**Issue by huahuayu** [miguelmota/cointop#126] opened 2021-04-28 08:26 UTC
first time start get `concurrent map writes` error, but the second-time start is ok. Maybe it's accidental.

```
brew install cointop && cointop
```

```text
[Q]Quit [?]Help [Enter]Chart [[ ]]Range [/]Search [C]Convert [F]Favorites [P]Portfolio [← →]Page 1/1                                                                                                        v1.6.5fatal error: concurrent map writes

goroutine 101 [running]:
runtime.throw(0x159383c, 0x15)
	runtime/panic.go:1117 +0x72 fp=0xc00055ddb8 sp=0xc00055dd88 pc=0x10372f2
runtime.mapassign_faststr(0x14fae80, 0xc0000d1650, 0xc0003da100, 0x10, 0x1918ea0)
	runtime/map_faststr.go:211 +0x3f1 fp=0xc00055de20 sp=0xc00055ddb8 pc=0x1015a91
github.com/miguelmota/cointop/pkg/filecache.(*FileCache).Set(0xc0000d1680, 0xc0003da100, 0x10, 0x1551d80, 0xc0001800f0, 0x4e94914f0000, 0x0, 0x0)
	github.com/miguelmota/cointop/pkg/filecache/filecache.go:60 +0x77c fp=0xc00055df38 sp=0xc00055de20 pc=0x137cc7c
github.com/miguelmota/cointop/cointop.(*Cointop).UpdateMarketbar.func1(0xc000380d00, 0xc0003da100, 0x10, 0xc0002a0030)
	github.com/miguelmota/cointop/cointop/marketbar.go:120 +0xbc fp=0xc00055dfc0 sp=0xc00055df38 pc=0x13df8fc
runtime.goexit()
	runtime/asm_amd64.s:1371 +0x1 fp=0xc00055dfc8 sp=0xc00055dfc0 pc=0x106d4e1
created by github.com/miguelmota/cointop/cointop.(*Cointop).UpdateMarketbar
	github.com/miguelmota/cointop/cointop/marketbar.go:119 +0x1985

goroutine 1 [select]:
github.com/miguelmota/gocui.(*Gui).MainLoop(0xc00039c000, 0x15b7110, 0xc000380d00)
	github.com/miguelmota/gocui@v0.4.2/gui.go:371 +0x14c
github.com/miguelmota/cointop/pkg/ui.(*UI).MainLoop(...)
	github.com/miguelmota/cointop/pkg/ui/ui.go:68
github.com/miguelmota/cointop/cointop.(*Cointop).Run(0xc000380d00, 0x0, 0x0)
	github.com/miguelmota/cointop/cointop/cointop.go:493 +0x2f1
github.com/miguelmota/cointop/cmd/commands.RootCmd.func1(0xc000396000, 0x1917780, 0x0, 0x0, 0x0, 0x0)
	github.com/miguelmota/cointop/cmd/commands/root.go:114 +0x336
github.com/spf13/cobra.(*Command).execute(0xc000396000, 0xc0001101f0, 0x0, 0x0, 0xc000396000, 0xc0001101f0)
	github.com/spf13/cobra@v1.0.0/command.go:842 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000396000, 0xc0001a5f28, 0x8, 0x8)
	github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.0.0/command.go:887
github.com/miguelmota/cointop/cmd/commands.Execute()
	github.com/miguelmota/cointop/cmd/commands/cmd.go:22 +0x178
main.main()
	github.com/miguelmota/cointop/main.go:8 +0x25

goroutine 22 [select]:
github.com/patrickmn/go-cache.(*janitor).Run(0xc0000d4460, 0xc000098300)
	github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1079 +0xa9
created by github.com/patrickmn/go-cache.runJanitor
	github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1099 +0xa9

goroutine 82 [select]:
github.com/miguelmota/termbox-go.Init.func1()
	github.com/miguelmota/termbox-go@v0.0.0-20191229070316-58d4fcbce2a7/api.go:98 +0x309
created by github.com/miguelmota/termbox-go.Init
	github.com/miguelmota/termbox-go@v0.0.0-20191229070316-58d4fcbce2a7/api.go:95 +0x710

goroutine 7 [IO wait]:
internal/poll.runtime_pollWait(0x29c6a998, 0x72, 0xffffffffffffffff)
	runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc00039a998, 0x72, 0x5000, 0x509e, 0xffffffffffffffff)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00039a980, 0xc000300000, 0x509e, 0x509e, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc00039a980, 0xc000300000, 0x509e, 0x509e, 0x4096, 0xc000301003, 0x5)
	net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000290000, 0xc000300000, 0x509e, 0x509e, 0x0, 0x0, 0x0)
	net/net.go:183 +0x91
crypto/tls.(*atLeastReader).Read(0xc00000e318, 0xc000300000, 0x509e, 0x509e, 0x4096, 0xc00005b200, 0x0)
	crypto/tls/conn.go:776 +0x63
bytes.(*Buffer).ReadFrom(0xc000294278, 0x162b6c0, 0xc00000e318, 0x100cbc5, 0x1507860, 0x156ad60)
	bytes/buffer.go:204 +0xbe
crypto/tls.(*Conn).readFromUntil(0xc000294000, 0x2a060008, 0xc000290000, 0x5, 0xc000290000, 0x9)
	crypto/tls/conn.go:798 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc000294000, 0x0, 0x0, 0x133509e)
	crypto/tls/conn.go:605 +0x115
crypto/tls.(*Conn).readRecord(...)
	crypto/tls/conn.go:573
crypto/tls.(*Conn).Read(0xc000294000, 0xc00035e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	crypto/tls/conn.go:1276 +0x165
bufio.(*Reader).Read(0xc00009b740, 0xc000551538, 0x9, 0x9, 0x12fc38b, 0xc000119c78, 0x10084a5)
	bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x162b560, 0xc00009b740, 0xc000551538, 0x9, 0x9, 0x9, 0xc0003cd0c0, 0xb81ab8e65b6300, 0xc0003cd0c0)
	io/io.go:328 +0x87
io.ReadFull(...)
	io/io.go:347
net/http.http2readFrameHeader(0xc000551538, 0x9, 0x9, 0x162b560, 0xc00009b740, 0x0, 0x0, 0xc0006982d0, 0x0)
	net/http/h2_bundle.go:1477 +0x89
net/http.(*http2Framer).ReadFrame(0xc000551500, 0xc0006982d0, 0x0, 0x0, 0x0)
	net/http/h2_bundle.go:1735 +0xa5
net/http.(*http2clientConnReadLoop).run(0xc000119fa8, 0x0, 0x0)
	net/http/h2_bundle.go:8322 +0xd8
net/http.(*http2ClientConn).readLoop(0xc000292600)
	net/http/h2_bundle.go:8244 +0x6f
created by net/http.(*http2Transport).newClientConn
	net/http/h2_bundle.go:7208 +0x6c5

goroutine 66 [syscall]:
os/signal.signal_recv(0x1630638)
	runtime/sigqueue.go:165 +0x9d
os/signal.loop()
	os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x45

goroutine 84 [chan receive]:
github.com/miguelmota/cointop/cointop.(*Cointop).PriceAlertWatcher(0xc000380d00, 0x0, 0x1917a00)
	github.com/miguelmota/cointop/cointop/price_alerts.go:165 +0x11f
created by github.com/miguelmota/cointop/cointop.(*Cointop).Run
	github.com/miguelmota/cointop/cointop/cointop.go:491 +0x2ca

goroutine 85 [select]:
github.com/miguelmota/termbox-go.PollEvent(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/miguelmota/termbox-go@v0.0.0-20191229070316-58d4fcbce2a7/api.go:342 +0x217
github.com/miguelmota/gocui.(*Gui).MainLoop.func1(0xc00039c000)
	github.com/miguelmota/gocui@v0.4.2/gui.go:354 +0x30
created by github.com/miguelmota/gocui.(*Gui).MainLoop
	github.com/miguelmota/gocui@v0.4.2/gui.go:352 +0x54

goroutine 86 [runnable]:
golang.org/x/text/internal/number.FormatDigits(0xc00013fa80, 0x10000, 0x10001000000, 0x0, 0xc0005d3890, 0x117a2ea, 0xc00013faa0, 0x0)
	golang.org/x/text@v0.3.3/internal/number/format.go:95 +0x125
golang.org/x/text/internal/number.(*Formatter).Format(0xc0002ea018, 0x0, 0x0, 0x0, 0xc00013fa80, 0x87c5c57f56908505, 0x87c5c57f56908505, 0x87c5c57f56908505)
	golang.org/x/text@v0.3.3/internal/number/format.go:103 +0x5a
golang.org/x/text/message.(*printer).fmtDecimalFloat(0xc0002ea000, 0x427ef2a1d4378cda, 0x40, 0x6)
	golang.org/x/text@v0.3.3/message/print.go:349 +0xd2
golang.org/x/text/message.(*printer).fmtFloat(0xc0002ea000, 0x427ef2a1d4378cda, 0x40, 0x66)
	golang.org/x/text@v0.3.3/message/print.go:237 +0x147
golang.org/x/text/message.(*printer).printArg(0xc0002ea000, 0x14d62a0, 0xc00048e3b8, 0x66)
	golang.org/x/text@v0.3.3/message/print.go:680 +0x371
golang.org/x/text/message.(*printer).doPrintf(0xc0002ea000, 0xc00048e3b0, 0x4)
	golang.org/x/text@v0.3.3/message/print.go:920 +0x154
golang.org/x/text/message.(*printer).Render(...)
	golang.org/x/text@v0.3.3/message/message.go:177
golang.org/x/text/message.lookupAndFormat(0xc0002ea000, 0x14da3e0, 0xc0005d3b80, 0xc0003cd9d0, 0x1, 0x1)
	golang.org/x/text@v0.3.3/message/message.go:153 +0x1aa
golang.org/x/text/message.(*Printer).Sprintf(0xc0003bc280, 0x14da3e0, 0xc0005d3b80, 0xc0003cd9d0, 0x1, 0x1, 0xc0003bc280, 0x0)
	golang.org/x/text@v0.3.3/message/message.go:114 +0x77
github.com/miguelmota/cointop/pkg/humanize.f(0x427ef2a1d4378cda, 0x1, 0x158cc10, 0xb, 0x0, 0xc0005901e0, 0x21)
	github.com/miguelmota/cointop/pkg/humanize/humanize.go:52 +0x2e6
github.com/miguelmota/cointop/pkg/humanize.Monetaryf(...)
	github.com/miguelmota/cointop/pkg/humanize/humanize.go:28
github.com/miguelmota/cointop/cointop.(*Cointop).UpdateMarketbar(0xc000380d00, 0x0, 0x0)
	github.com/miguelmota/cointop/cointop/marketbar.go:152 +0x11c9
github.com/miguelmota/cointop/cointop.(*Cointop).layout.func1(0xc000380d00)
	github.com/miguelmota/cointop/cointop/layout.go:65 +0x2f
created by github.com/miguelmota/cointop/cointop.(*Cointop).layout
	github.com/miguelmota/cointop/cointop/layout.go:64 +0x1131

goroutine 87 [select]:
net/http.(*Transport).getConn(0x18df5a0, 0xc0002dc040, 0x0, 0xc0002a60c0, 0x5, 0xc00096c810, 0x15, 0x0, 0x0, 0x0, ...)
	net/http/transport.go:1368 +0x589
net/http.(*Transport).roundTrip(0x18df5a0, 0xc000494000, 0x30, 0x1561b80, 0xc000117350)
	net/http/transport.go:579 +0x7eb
net/http.(*Transport).RoundTrip(0x18df5a0, 0xc000494000, 0x18df5a0, 0x0, 0x0)
	net/http/roundtrip.go:17 +0x35
net/http.send(0xc000494000, 0x162bbc0, 0x18df5a0, 0x0, 0x0, 0x0, 0xc0007e0020, 0x2a7874c8, 0x1, 0x0)
	net/http/client.go:251 +0x454
net/http.(*Client).send(0x18e87a0, 0xc000494000, 0x0, 0x0, 0x0, 0xc0007e0020, 0x0, 0x1, 0x191b228)
	net/http/client.go:175 +0xff
net/http.(*Client).do(0x18e87a0, 0xc000494000, 0x0, 0x0, 0x0)
	net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
	net/http/client.go:585
github.com/miguelmota/cointop/pkg/api/vendors/coingecko/v3.doReq(0xc000494000, 0x18e87a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/miguelmota/cointop/pkg/api/vendors/coingecko/v3/v3.go:34 +0x69
github.com/miguelmota/cointop/pkg/api/vendors/coingecko/v3.(*Client).MakeReq(0xc0000de0b8, 0xc0002a60c0, 0x5d, 0x1, 0x1, 0xc0002a60c0, 0x5d, 0x1)
	github.com/miguelmota/cointop/pkg/api/vendors/coingecko/v3/v3.go:56 +0x9f
github.com/miguelmota/cointop/pkg/api/vendors/coingecko/v3.(*Client).GlobalCharts(0xc0000de0b8, 0xc0003a40fa, 0x3, 0xc0003a40f7, 0x3, 0x17789b2000000017, 0x60891b33, 0xc0005b3aa0)
	github.com/miguelmota/cointop/pkg/api/vendors/coingecko/v3/v3.go:375 +0x34a
github.com/miguelmota/cointop/pkg/api/impl/coingecko.(*Service).GetGlobalMarketGraphData(0xc0000986c0, 0xc0000d8670, 0x3, 0x5ece2333, 0x60891b33, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/miguelmota/cointop/pkg/api/impl/coingecko/coingecko.go:157 +0x11f
github.com/miguelmota/cointop/cointop.(*Cointop).ChartPoints(0xc000380d00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/miguelmota/cointop/cointop/chart.go:141 +0x50d
github.com/miguelmota/cointop/cointop.(*Cointop).UpdateChart(0xc000380d00, 0x0, 0x0)
	github.com/miguelmota/cointop/cointop/chart.go:72 +0x145
github.com/miguelmota/cointop/cointop.(*Cointop).layout.func2(0xc000380d00)
	github.com/miguelmota/cointop/cointop/layout.go:99 +0x32
created by github.com/miguelmota/cointop/cointop.(*Cointop).layout
	github.com/miguelmota/cointop/cointop/layout.go:98 +0xf52

goroutine 89 [chan receive]:
github.com/miguelmota/cointop/cointop.(*Cointop).UpdateCoins(0xc000380d00, 0x0, 0x0)
	github.com/miguelmota/cointop/cointop/list.go:38 +0x265
github.com/miguelmota/cointop/cointop.(*Cointop).layout.func3(0xc000380d00)
	github.com/miguelmota/cointop/cointop/layout.go:144 +0x2b
created by github.com/miguelmota/cointop/cointop.(*Cointop).layout
	github.com/miguelmota/cointop/cointop/layout.go:143 +0xcc7

goroutine 91 [select]:
github.com/miguelmota/cointop/cointop.(*Cointop).intervalFetchData.func1(0xc000380d00)
	github.com/miguelmota/cointop/cointop/refresh.go:63 +0x79
created by github.com/miguelmota/cointop/cointop.(*Cointop).intervalFetchData
	github.com/miguelmota/cointop/cointop/refresh.go:61 +0x4c

goroutine 92 [chan receive]:
github.com/miguelmota/cointop/cointop.(*Cointop).Refresh.func1(0xc000380d00)
	github.com/miguelmota/cointop/cointop/refresh.go:12 +0x3b
created by github.com/miguelmota/cointop/cointop.(*Cointop).Refresh
	github.com/miguelmota/cointop/cointop/refresh.go:11 +0x4c

goroutine 31 [runnable]:
golang.org/x/text/message.(*printer).fmtDecimalFloat(0xc000328380, 0x427ef2a1d4378cda, 0x40, 0x6)
	golang.org/x/text@v0.3.3/message/print.go:342 +0x31
golang.org/x/text/message.(*printer).fmtFloat(0xc000328380, 0x427ef2a1d4378cda, 0x40, 0x66)
	golang.org/x/text@v0.3.3/message/print.go:237 +0x147
golang.org/x/text/message.(*printer).printArg(0xc000328380, 0x14d62a0, 0xc0003a4f88, 0x66)
	golang.org/x/text@v0.3.3/message/print.go:680 +0x371
golang.org/x/text/message.(*printer).doPrintf(0xc000328380, 0xc0003a4f84, 0x4)
	golang.org/x/text@v0.3.3/message/print.go:920 +0x154
golang.org/x/text/message.(*printer).Render(...)
	golang.org/x/text@v0.3.3/message/message.go:177
golang.org/x/text/message.lookupAndFormat(0xc000328380, 0x14da3e0, 0xc0005c7bb0, 0xc000476b60, 0x1, 0x1)
	golang.org/x/text@v0.3.3/message/message.go:153 +0x1aa
golang.org/x/text/message.(*Printer).Sprintf(0xc0004fa0a0, 0x14da3e0, 0xc0005c7bb0, 0xc000476b60, 0x1, 0x1, 0xc0004fa0a0, 0x0)
	golang.org/x/text@v0.3.3/message/message.go:114 +0x77
github.com/miguelmota/cointop/pkg/humanize.f(0x427ef2a1d4378cda, 0x1, 0x158cc10, 0xb, 0x0, 0xc0007f60c0, 0x21)
	github.com/miguelmota/cointop/pkg/humanize/humanize.go:52 +0x2e6
github.com/miguelmota/cointop/pkg/humanize.Monetaryf(...)
	github.com/miguelmota/cointop/pkg/humanize/humanize.go:28
github.com/miguelmota/cointop/cointop.(*Cointop).UpdateMarketbar(0xc000380d00, 0x5, 0xc0006a1ea0)
	github.com/miguelmota/cointop/cointop/marketbar.go:152 +0x11c9
created by github.com/miguelmota/cointop/cointop.(*Cointop).ChartPoints
	github.com/miguelmota/cointop/cointop/chart.go:107 +0xe5

goroutine 32 [chan receive]:
net/http.(*persistConn).addTLS(0xc0003de000, 0xc00096c810, 0x11, 0x0, 0xc00096c822, 0x3)
	net/http/transport.go:1536 +0x21f
net/http.(*Transport).dialConn(0x18df5a0, 0x1634610, 0xc000130010, 0x0, 0xc0002a60c0, 0x5, 0xc00096c810, 0x15, 0x0, 0xc0003de000, ...)
	net/http/transport.go:1610 +0x1e05
net/http.(*Transport).dialConnFor(0x18df5a0, 0xc000398210)
	net/http/transport.go:1442 +0xc6
created by net/http.(*Transport).queueForDial
	net/http/transport.go:1411 +0x40f

goroutine 94 [IO wait]:
internal/poll.runtime_pollWait(0x29c6a8b0, 0x72, 0xffffffffffffffff)
	runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0002e8098, 0x72, 0x200, 0x205, 0xffffffffffffffff)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0002e8080, 0xc000545d40, 0x205, 0x205, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc0002e8080, 0xc000545d40, 0x205, 0x205, 0xc0005a6000, 0x10000c000363496, 0x2a078e98)
	net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0003fe0b0, 0xc000545d40, 0x205, 0x205, 0x0, 0x0, 0x0)
	net/net.go:183 +0x91
crypto/tls.(*atLeastReader).Read(0xc00000e108, 0xc000545d40, 0x205, 0x205, 0x10f9aba, 0xc000580480, 0x0)
	crypto/tls/conn.go:776 +0x63
bytes.(*Buffer).ReadFrom(0xc0002953f8, 0x162b6c0, 0xc00000e108, 0x100cbc5, 0x1507860, 0x156ad60)
	bytes/buffer.go:204 +0xbe
crypto/tls.(*Conn).readFromUntil(0xc000295180, 0x2a060008, 0xc0003fe0b0, 0x5, 0xc0003fe0b0, 0x0)
	crypto/tls/conn.go:798 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc000295180, 0x0, 0x11a, 0x11a)
	crypto/tls/conn.go:605 +0x115
crypto/tls.(*Conn).readRecord(...)
	crypto/tls/conn.go:573
crypto/tls.(*Conn).readHandshake(0xc000295180, 0xc0005a6016, 0xc0005a6000, 0x11a, 0x180)
	crypto/tls/conn.go:1008 +0x6d
crypto/tls.(*Conn).clientHandshake(0xc000295180, 0x0, 0x0)
	crypto/tls/handshake_client.go:171 +0x2aa
crypto/tls.(*Conn).Handshake(0xc000295180, 0x0, 0x0)
	crypto/tls/conn.go:1391 +0xc9
net/http.(*persistConn).addTLS.func2(0x0, 0xc000295180, 0xc0005400a0, 0xc0003a2180)
	net/http/transport.go:1530 +0x45
created by net/http.(*persistConn).addTLS
	net/http/transport.go:1526 +0x1f6

goroutine 57 [runnable]:
bufio.(*Reader).ReadByte(0xc0003a2120, 0xc0007104db, 0x0, 0x0)
	bufio/bufio.go:247 +0xd5
compress/flate.(*decompressor).huffSym(0xc0003ee000, 0xc0003ee028, 0x61, 0x0, 0x0)
	compress/flate/inflate.go:719 +0x85
compress/flate.(*decompressor).huffmanBlock(0xc0003ee000)
	compress/flate/inflate.go:494 +0xd2
compress/flate.(*decompressor).Read(0xc0003ee000, 0xc000d56000, 0x4000, 0x4000, 0xc000, 0x20bf411, 0x0)
	compress/flate/inflate.go:347 +0x79
compress/gzip.(*Reader).Read(0xc0001b2dc0, 0xc000d56000, 0x4000, 0x4000, 0x8000, 0x0, 0x0)
	compress/gzip/gunzip.go:251 +0x87
net/http.(*http2gzipReader).Read(0xc0003d3d40, 0xc000d56000, 0x4000, 0x4000, 0x8000, 0x0, 0x0)
	net/http/h2_bundle.go:9080 +0x69
io.ReadAll(0x29ca4c98, 0xc0003d3d40, 0xc0003d3d40, 0x29ca4c98, 0xc0003d3d40, 0xc000575760, 0x1084b7c)
	io/io.go:633 +0xdf
io/ioutil.ReadAll(...)
	io/ioutil/ioutil.go:27
github.com/miguelmota/cointop/pkg/api/vendors/coingecko/v3.doReq(0xc0009b0000, 0x18e87a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/miguelmota/cointop/pkg/api/vendors/coingecko/v3/v3.go:39 +0xe5
github.com/miguelmota/cointop/pkg/api/vendors/coingecko/v3.(*Client).MakeReq(0xc0000de0b8, 0xc0002c40b0, 0xa4, 0x2, 0x2, 0xc0002c40b0, 0xa4, 0x1)
	github.com/miguelmota/cointop/pkg/api/vendors/coingecko/v3/v3.go:56 +0x9f
github.com/miguelmota/cointop/pkg/api/vendors/coingecko/v3.(*Client).CoinsMarket(0xc0000de0b8, 0xc000426030, 0x3, 0x1917780, 0x0, 0x0, 0x158f975, 0xf, 0xfa, 0x1, ...)
	github.com/miguelmota/cointop/pkg/api/vendors/coingecko/v3/v3.go:182 +0x55e
github.com/miguelmota/cointop/pkg/api/impl/coingecko.(*Service).getPaginatedCoinData(0xc0000986c0, 0xc0000d8670, 0x3, 0x0, 0xc000575f78, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/miguelmota/cointop/pkg/api/impl/coingecko/coingecko.go:357 +0x2c9
github.com/miguelmota/cointop/pkg/api/impl/coingecko.(*Service).GetAllCoinData.func1(0xc0001003c0, 0xc0000986c0, 0xc0000d8670, 0x3)
	github.com/miguelmota/cointop/pkg/api/impl/coingecko/coingecko.go:83 +0x111
created by github.com/miguelmota/cointop/pkg/api/impl/coingecko.(*Service).GetAllCoinData
	github.com/miguelmota/cointop/pkg/api/impl/coingecko/coingecko.go:75 +0x5d

goroutine 97 [runnable]:
regexp/syntax.(*parser).concat(0xc000636060, 0x158ecfd)
	regexp/syntax/parse.go:291 +0x1a5
regexp/syntax.Parse(0x158ecfd, 0xe, 0x2a7800d4, 0x2a56fc10, 0xc000643da8, 0x100ef7b)
	regexp/syntax/parse.go:885 +0x10b0
regexp.compile(0x158ecfd, 0xe, 0xc0000000d4, 0x1015a2b, 0xd0, 0x1539c40)
	regexp/regexp.go:170 +0x5a
regexp.Compile(...)
	regexp/regexp.go:133
regexp.MustCompile(0x158ecfd, 0xe, 0xc0002be2f0)
	regexp/regexp.go:309 +0x4b
github.com/miguelmota/cointop/pkg/filecache.(*FileCache).Set(0xc0000d1680, 0xc0002be2f0, 0x10, 0x1551d80, 0xc000638000, 0x4e94914f0000, 0x0, 0x0)
	github.com/miguelmota/cointop/pkg/filecache/filecache.go:66 +0x185
github.com/miguelmota/cointop/cointop.(*Cointop).UpdateMarketbar.func1(0xc000380d00, 0xc0002be2f0, 0x10, 0xc000180000)
	github.com/miguelmota/cointop/cointop/marketbar.go:120 +0xbc
created by github.com/miguelmota/cointop/cointop.(*Cointop).UpdateMarketbar
	github.com/miguelmota/cointop/cointop/marketbar.go:119 +0x1985
```

**Comment by lyricnz** [comment] 2021-08-31 08:28
Could not reproduce. Uninstalled cointop, cleaned homebrew, ran "brew install cointop && cointop" no problem.

**Comment by miguelmota** [comment] 2021-09-07 07:35
Closed by https://github.com/miguelmota/cointop/pull/133/files

**Closed by miguelmota** 2021-09-07 07:35 UTC
Labels: bug
