### ISSUE TITLE
Portfolio charts not updating anymore

### ISSUE THREAD

**Issue by YoannPa** [miguelmota/cointop#105] opened 2021-04-09 18:31 UTC
For some reason the charts available in my portfolio are not updated anymore.
The cryptocurrentcy values, and changes seem to still be updated correctly, but the display is not updated anymore and it doesn't reflect these changes anymore.
I can see that since the charts for the same cryptocurrency are different between the portfolio and the main menu with all currencies.

How to fix this ?

**Comment by YoannPa** [comment] 2021-04-16 13:11
As an additionnal comment: restarting the computer fixed it.
I am using Ubuntu 16.04.
Is there another way to fix this without restarting the whole computer ?

**Comment by simon-anz** [comment] 2021-08-18 02:44
Possibly a duplicate of #108 ?

**Comment by miguelmota** [comment] 2021-08-22 10:07
Closed by https://github.com/miguelmota/cointop/pull/137

**Closed by miguelmota** 2021-08-22 10:07 UTC
Labels: bug
