### ISSUE TITLE
Portfolio | Duplicate XRP rows

### ISSUE THREAD

**Issue by tetsuo76** [miguelmota/cointop#130] opened 2021-05-14 11:42 UTC
Hello,

Eveytime I am adding XRP in my portfolio I am getting 1 or 2 extra "Binance-Peg XRP" rows which I can't remove. I tried changing the holdings value to zero but they still appear on the list. Is there a way to remove them?

![Screenshot-20210514143606-546x100](https://user-images.githubusercontent.com/5783637/118265829-6c62c700-b4c2-11eb-9fb3-391ca9e7ae13.png)

**Comment by miguelmota** [comment] 2021-05-14 19:57
@tetsuo76 Thanks for the bug report! 

Will try to get this fixed as soon as time allows.

To get rid of the 0 amount rows, edit the entry and set it to an empty value (not 0), or alternatively delete the entry from the config file.

**Comment by tetsuo76** [comment] 2021-05-15 09:01
Hi Miguel, thanks for your quick reply. I tried to set it to an empty value but then it takes the holdings value of the plain XRP.

![Screenshot-20210515115454-553x30](https://user-images.githubusercontent.com/5783637/118354729-2fa3d800-b575-11eb-9a45-0e198b4f4dd5.png)

I also checked the config file but "Binance-Peg XRP" doesn't exist in [portfolio].

I guess I'll have to wait for a fix. (I am using the snap version btw)

**Comment by TheBigLaskowski** [comment] 2021-05-17 14:05
enter 0.0 for the value and it will keep the entry listed, however your portfolio value will be accurate again. until the fix is released anyway

**Comment by simon-anz** [comment] 2021-08-17 01:26
I have the same issue, also caused by the duplicate/double-named coins. Eg:

```
$ cointop holdings
           name	symbol	price	holdings	balance	 24h%	%holdings
EOS            	EOS   	 5.39	      50	  269.5	-7.40	    38.52
Binance-Peg EOS	EOS   	 5.29	      50	  264.5	-9.11	    37.81
Cardano        	ADA   	 2.07	      40	   82.8	-3.81	    11.84
Cardano        	ADA   	 2.07	      40	   82.8	-3.83	    11.84
```

**Comment by simon-anz** [comment] 2021-08-17 02:21
I don't know how to write golang, but this worked for me. It just skips adding duplicate entries to the portfolio slice.

```
$ git diff
diff --git a/cointop/portfolio.go b/cointop/portfolio.go
index 58ab85c..d46b980 100644
--- a/cointop/portfolio.go
+++ b/cointop/portfolio.go
@@ -529,12 +529,20 @@ func (ct *Cointop) GetPortfolioSlice() []*Coin {
                return sliced
        }

+OUTER:
        for i := range ct.State.allCoins {
                coin := ct.State.allCoins[i]
                p, isNew := ct.PortfolioEntry(coin)
                if isNew {
                        continue
                }
+               // check not already found
+               for j := range sliced {
+                       if coin.Symbol == sliced[j].Symbol {
+                               continue OUTER
+                       }
+               }
+
                coin.Holdings = p.Holdings
                balance := coin.Price * p.Holdings
                balancestr := fmt.Sprintf("%.2f", balance)
```

**Comment by simon-anz** [comment] 2021-08-19 00:52
This doesn't seem to be the complete fix.  When viewing the portfolio, and changing between currency conversions, sometimes it picks a different rate. Suspect we're looping through a list of coins without a stable sort.

**Comment by simon-anz** [comment] 2021-08-19 01:55
There are many duplicates in ct.State.allCoins - often two, but some up to seven (SCC). Sorting by Rank would be a good first-guess, but there are some surprises with that. For example: Binance-Peg EOS (rank 10) is lower than EOS itself (rank 34)

Updated PR to use the highest-rank coin found, updating slice if required.

**Comment by miguelmota** [comment] 2021-08-22 11:11
Closed by https://github.com/miguelmota/cointop/pull/138

**Closed by miguelmota** 2021-08-22 11:11 UTC
Labels: bug
