### ISSUE TITLE
macOS default config in ~/Library/Application Support/cointop

### ISSUE THREAD

**Issue by GETandSELECT** [miguelmota/cointop#85] opened 2021-02-11 15:56 UTC
In macOS the default config file not in `~/.config/cointop/config.toml`, instead `~/Library/Application Support/cointop/config.toml`. 
I prefer `~/.config/cointop/config.toml`, but don't know if this is macOS standard

**Comment by miguelmota** [comment] 2021-02-12 09:03
Thanks for the bug report! Seems to be related to a recent macOS or homebrew update since a few users have reported similar reports on macOS, but not sure. Will take a look!

**Comment by afh** [comment] 2021-04-19 19:45
This stems from the use of `os.UserConfigDir()` in [`pkg/pathutil/pathutil.go:13`](https://github.com/miguelmota/cointop/blob/51cb44269832e9cceada2051b3669b72cd42dfa5/pkg/pathutil/pathutil.go#L13); the the [documentation of `os.UserConfigDir`](https://pkg.go.dev/os#UserConfigDir) mentions:
>  On Darwin, it returns $HOME/Library/Application Support

**Comment by miguelmota** [comment] 2021-04-25 20:18
Hi @GETandSELECT,

@afh is correct.

There are two ways to change config file path in this case;

Use flag:

```bash
cointop --config ~/.config/cointop/config.toml
```

Or use environment variable:

```bash
export COINTOP_CONFIG=~/.config/cointop/config.toml
cointop
```

Closing since this is expected behavior of `os.UserConfigDir()`

**Closed** 2021-04-25 20:18 UTC
Labels: bug
